### ISSUE TITLE
What does the alias "onp" stand for?

### ISSUE THREAD

**Issue by shoyer** [seberg/numpy-dispatch#2]
I agree that a short alias is a good idea to encourage for readable code, but I'm not quite sure where this name comes from.

There is also a loose convention in parts of the JAX codebase (which we are trying to remove) to use "import numpy as onp" to refer to "original" NumPy.

**Comment by seberg** [comment]
Hehehe, yeah I was curious about it myself :). I think it is just something we used in the last dev-meeting. "other" maybe.
So yes, we need a better name when we actually go here to pass on best practices. `nx` borrowing from the old `numerix` name that NumPy never got may be an option? Or `npx` to hint to (cross) compatibility, even if that may not be quite the right term?

**Comment by seberg** [comment]
ISTR that @hameerabbasi used `onp` first in this context?

**Comment by hameerabbasi** [comment]
Yes, I used `import unumpy as np` and `import numpy as onp` for "Original NumPy".

**Comment by seberg** [comment]
Hehe, so the `onp` was either just a mix-up we kept using during that meeting or I misremembered that we used it in this context :). I think `npx` may be a reasonable spelling though?

**Comment by seberg** [comment]
I think I changed this to xnp, so closing for now.

**Comment by shoyer** [comment]
> I think I changed this to xnp, so closing for now.

you mean `npx`, right? `xnp` would probably also be fine, though :)
