### ISSUE TITLE
Why is end-user opt-in required with this package?

### ISSUE THREAD

**Issue by shoyer** [seberg/numpy-dispatch#6]
The readme says this was "an early thought when scikit-learn experimented with using this type of functionality"

To me this feels like a layer that should live downstream e.g., in Scikit-Learn with  [`sklearn.set_config`](https://scikit-learn.org/stable/modules/generated/sklearn.set_config.html). I appreciate that it can make sense for end-users to opt-in to breaking changes, but I think this really is a decision to make on a library-by-library basis.

The problem is that as soon as this global switch is used for compatibility with one library, it's useless for others. For example, suppose sklearn adds experimental dispatch support recommending that users opt-in. If matplotlib adds dispatching later, some of its users will have already opted into dispatching for sklearn, even though they may not have updated their matplotlib code.

That said, NEP 37 should probably add a recommendation for library authors considering using `get_array_module()` to consider adding their opt-in mechanism. We could probably even include an example of how to do so in a concurrency fashion using `contextvars`.

**Comment by rgommers** [comment]
That may turn into a mess. If every library uses its own switch, implemented differently, a user may have to set many to make things work. Also if libraries depend on each other, the switch won't propagate. E.g. scikit-learn depends on SciPy, which may also have a switch in your proposal, but the user doesn't see this dependency - they just interact with scikit-learn.

I think once a user uses, e.g., CuPy and wants to opt-in to dispatching, I think they want to opt in for all libraries that support it.

**Comment by shoyer** [comment]
> Also if libraries depend on each other, the switch won't propagate. E.g. scikit-learn depends on SciPy, which may also have a switch in your proposal, but the user doesn't see this dependency - they just interact with scikit-learn.

If sklearn wants to selectively enable disabling, it indeed would have to selectively enable dispatching within SciPy functions. This could be done with wrapper function, perhaps something like:
```python
def sklearn_wrapper_of_scipy_function(*args, **kwargs):
    if sklearn.get_config()['dispatching_enabled']:
        with scipy.config_context(dispatching_enabled=True):
            return scipy_function(*args, **kwargs)
    else:
        return scipy_function(*args, **kwargs)
```

So far, this works fine as every upstream library also supplies context manager for enabling dispatch, and as long as scipy doesn't internally call back into sklearn.

The tricky case is for higher order functions like `scipy.optimize.minimize(fun, x0, ...)`. If `fun` internally expects sklearn and/or scipy to have dispatching disabled, it could break. I guess this could be solved by selectively _disabling_ dispatch whenever calling into other libraries, e.g.,
```python
def sklearn_wrapper_of_scipy_minimize(fun, x0, **kwargs):
    if sklearn.get_config()['dispatching_enabled']:
        with sklearn.config_context(dispatching_enabled=False):
            with scipy.config_context(dispatching_enabled=True):
                # scipy.optimize.minimize would need to do a similar dance when calling fun()
                return scipy.optimize.minimize(fun, x0, **kwargs)
    else:
        return scipy.optimize.minimize(fun, x0, **kwargs)
```

This is certainly plenty of trouble for a (hopefully short?) transition. But it does manage to preserve both "explicit local control" (generally a good principle of software design) and a deprecation cycle for libraries that care about that.

> I think once a user uses, e.g., CuPy and wants to opt-in to dispatching, I think they want to opt in for all libraries that support it.

I think it really depends on how fast this transition happens. If we really think that every library that could use `get_array_module()` is going to add support at around the same time, then sure, users would find it convenient to have a single option for enabling them all at once.

But if instead `get_array_module()` rolls out over a number of years (which personally I think is more likely), then pushing all libraries onto the same migration timeline is not helpful. Either the opt-in mechanism eventually goes away, or users have already enabled it for libraries that were "early adopters" of `get_array_module()`. Either way, it's not useful for "late adopters" of `get_array_module()` concerned about suddenly breaking existing user code.

(Note: I expect _implementation_ of `__array_module__` could roll out much faster in duck array libraries, e.g., in a matter of a few months. Writing generic code that works across a suite of duck arrays is much harder, though.)

**Comment by shoyer** [comment]
That said, my main complaint is just that this makes this a little more annoying for *new* projects to use `get_array_module()`.

But I guess then can always write their own helper function to use, too, e.g.,
```python
def get_array_module(*arrays):
    with numpy_dispatch.ensure_dispatching():
        return numpy_dispatch.get_array_module(*arrays)
```

**Comment by rgommers** [comment]
> But if instead `get_array_module()` rolls out over a number of years (which personally I think is more likely), 

I agree that that's more likely.

> then pushing all libraries onto the same migration timeline is not helpful.

That's not what that would do I believe. It's already opt-in and _staying_ opt-in is my understanding. Meaning the majority of users won't be using it, and for the ones that do they'll probably be fine even in a staggered introduction (it's not like libraries like SciPy and Matplotlib are in the habit of rolling out completely untested/buggy changes). And if you want to be doubly sure we could explain how it works in docs and suggest pinning library version for example.

The staying opt-in is maybe what needs clarifying. Were you thinking that scikit-learn would provide the switch and then flip it from `False` to `True` after a release or two? My comment above assumes it stays `False`.

**Comment by seberg** [comment]
Indeed, the question is of transition vs. the actual end-state (EDIT: the switch is only relevent for the end-state).  A project may support it only as "experimental", but then flip the switch on it later.  I do not think the global switch does solves the issue of transitioning.

So yes, this may assume that the default will remain `True` basically indefinitely.  And @shoyer is right there, that does seem inconvenient for many projects.  I guess that is why I added the `enabled=None` flag to the `get_array_module()` function right now, to conveniently override it.

**Comment by seberg** [comment]
Damnit: The current code would assume that many libraries want to default to `False` indefinitely, and require the opt-in.  The `enabled=True`, was a way for libraries to ignore this (at this time).  I do not have much of an opinion about whether that is the right choice.  It might be, but then I am also not sure if it is not actually less disruptive in the long-run if we just switch over gently and slowly (instead of always having a confusing switch).

As @rgommers said, I think the transitioning problem itself is fairly distinct from this global switch.

**Comment by shoyer** [comment]
> The staying opt-in is maybe what needs clarifying. Were you thinking that scikit-learn would provide the switch and then flip it from `False` to `True` after a release or two? My comment above assumes it stays `False`.

Yes, this is what I was assuming. In the long term, requiring explicit opt-in for `get_array_module()` seems like it would be annoying for both users and maintainers. Most projects try to keep the number of global options to the bare minimum precisely because of this maintenance burden (e.g., all code needs to be tested with both configurations).

**Comment by rgommers** [comment]
> In the long term, requiring explicit opt-in for `get_array_module()` seems like it would be annoying for both users and maintainers.

I completely agree. But if the reason for the switch is backwards compat (which I believe it was here), then I don't see there's ever a good time to change the default. Well, maybe in a major release, but that could take a long time for each lib.

**Comment by seberg** [comment]
Squinting at it, I think we should switch the default in the `np.get_array_module()` function to `True` instead of `None`, though.  The flag was first there to not run into back-compat issues, but since I do not believe it helps with transitions, I have my doubts it should be used by default.  I.e. many libraries may use it for an "experimental" phase, but it is undesirable that the end-state would use `enabled=True` everywhere.

This flag makes sense not so much for transitioning, but to make it truly opt-in (because it is experimental, e.g. partial support only).  So the global setting may be useful for the daring users only in that regard (it should probably be considered dangerous and not exist).

As for a library: If a library uses requires "enabling" (during an experimental phase), it will still need to do proper *transitioning* of users after flipping the switch.

**Comment by shoyer** [comment]
I'm a little skeptical that it would be useful, but it would certainly be harmless to include an end-user opt-in mechanism as an option for libraries that want it (as long as the default version of `get_array_module()` does not require it).

**Comment by seberg** [comment]
Can't say I disagree, but right now I am willing to just see whats possible and hope library-authors can get a feel of what is useful and what is not.

Will close this for now, since I switched the default (not sure if the `opt_in=True` name is great).  There is a potential issue that opting-in like this should probably also hide any `FutureWarning`s, but I will defer that to a time where anyone actually thinks that `FutureWarning`s as done here might be useful, they are after all just a thought.
